Admin - Category - Update Category
AT-PHPIntership/food-market-order pull request #100
Opened 2017-08-05 13:16 UTC by at-vudang

2017-08-07 11:01 UTC, at-duyho commented on app/Http/Controllers/CategoryController.php
>  class CategoryController extends Controller
you should create constructor to use DI laravel.

2017-08-07 11:01 UTC, at-duyho commented on app/Http/Controllers/CategoryController.php
> +        $category = Category::find($id);
you should use findOrFail function

2017-08-07 11:01 UTC, at-duyho commented on app/Http/Controllers/CategoryController.php
> +        $category = Category::find($id);
you should use findOrFail function.

2017-08-07 11:02 UTC, at-duyho commented on app/Http/Controllers/CategoryController.php
> +        $category->name = $request->categoryName;
you should validate data.

2017-08-07 11:02 UTC, ghost requested changes
check my comment. thank you!

2017-08-08 02:01 UTC, at-duyho commented on app/Http/Controllers/CategoryController.php
> +        $this->category = $cate;
-you should define clear variable: $cate => $category

2017-08-08 02:05 UTC, at-duyho commented on app/Http/Controllers/CategoryController.php
> +        $this->validate($request, [
-you should create a new Request class to validate data.

2017-08-08 02:06 UTC, at-duyho commented on app/Http/Controllers/CategoryController.php
> +        $cate =  $this->category->findOrFail($id);
-you should define clear variable: $cate => $category

2017-08-08 02:07 UTC, ghost requested changes
Check comment and fix permission file (10664->100755)

2017-08-08 08:36 UTC, at-duyho commented on app/Http/Controllers/CategoryController.php
> +        $category->save();
-you should use: $this->update($request->all());

2017-08-08 08:37 UTC, ghost requested changes
Check comment. thank!

2017-08-08 08:42 UTC, at-duyho commented on app/Http/Requests/CategoryRequest.php
> +           'description' => 'required',
do description require?

2017-08-08 08:51 UTC, at-vudang commented on app/Http/Requests/CategoryRequest.php
> +           'description' => 'required',
No, I will remove.

2017-08-08 10:43 UTC, ghost approved these changes
LGTM

2017-08-10 02:46 UTC, ghost requested changes
I see the fatal error in this PR, please fix and please test on your local before assign reviewer

2017-08-10 07:46 UTC, at-vudang commented
I merged, fixed and tested in local. Please you check again it. Thank you!

2017-08-10 08:30 UTC, ghost approved these changes
LGTM

2017-08-10 08:30 UTC, merged