Admin Create Daily Menu
AT-PHPIntership/food-market-order pull request #111
Opened 2017-08-10 09:39 UTC by at-hungnguyen

2017-08-11 02:27 UTC, at-duyho commented on app/DailyMenu.php
> +     * @return relationship
@return Illuminate\Database\Eloquent\Relations\BelongsTo

2017-08-11 02:29 UTC, at-duyho commented on app/Http/Controllers/DailyMenuController.php
> +            $category = $request->category;
$category or $category_id?

2017-08-11 02:43 UTC, ghost commented on app/Http/Controllers/DailyMenuController.php
> +        if (sizeof($this->dailyMenu->where('date', $date)->where('food_id', $foodId))>1) {
you should use check exist by querybuilder.

2017-08-11 02:44 UTC, at-duyho commented on app/Http/Controllers/DailyMenuController.php
> +            $oldQuantity = $this->dailyMenu
you should use firstOrFail() instead of get()[0].

2017-08-11 02:44 UTC, ghost requested changes
check comment.

2017-08-11 06:35 UTC, at-hungnguyen commented
I have updated, please check it again!
Thank you so much

2017-08-11 07:13 UTC, at-duyho commented on app/Http/Controllers/DailyMenuController.php
> +            $oldQuantity = $dailyMenu->first()['quantity'];
$dailyMenu->first()->quantity

2017-08-11 07:21 UTC, at-duyho commented on app/Http/Controllers/DailyMenuController.php
> +        $dailyMenu = $this->dailyMenu->where('date', $date)->where('food_id', $foodId);
you should use firstOrFail()

2017-08-11 07:22 UTC, at-duyho commented on app/Http/Controllers/DailyMenuController.php
> +        if ($dailyMenu->count()) {
you should use firstOrFail() function.

2017-08-11 07:27 UTC, ghost requested changes
Check comment

2017-08-14 02:44 UTC, at-duyho commented on resources/views/daily_menus/create.blade.php
> +                  @if(!empty($date))
why don't you use positive condition?

2017-08-14 02:47 UTC, ghost requested changes
check comment.

2017-08-14 14:28 UTC, at-hungnguyen commented
I have updated Ajax request for Food List, please check it again
Thank you so much!

2017-08-15 09:06 UTC, ghost approved these changes
fix conflict

2017-08-15 09:26 UTC, ghost approved these changes
LGTM

2017-08-15 10:04 UTC, ghost approved these changes

2017-08-15 10:04 UTC, merged