Admin - Test - List Daily Menu
AT-PHPIntership/food-market-order pull request #123
Opened 2017-08-16 08:13 UTC by at-hungnguyen

2017-08-17 01:57 UTC, at-duyho commented on tests/Browser/DailyMenu/ListTest.php
> +    public function testObject10()
what's testObject10? I don't understand it.

2017-08-17 01:57 UTC, at-duyho commented on tests/Browser/DailyMenu/ListTest.php
> +    public function testObject11()
what't testObject11?

2017-08-17 01:58 UTC, ghost requested changes
check comment

2017-08-22 01:35 UTC, at-hungnguyen commented
I have updated, please check it again.
Thank you so much!

2017-08-23 04:19 UTC, ghost reviewed
Please check my comment. You need to add case test when list empty.

2017-08-23 04:19 UTC, at-vietpham commented on tests/Browser/AdminListDailyMenuTest.php
> +            $objectCount = $browser->elements('.table tr');
You can check with element `.table tbody tr` to get correct data record.

2017-08-23 04:19 UTC, at-vietpham commented on tests/Browser/AdminListDailyMenuTest.php
> +    public function testPaginationWith10Rows()
You want to test list has one page right?. If correct, you should be change function name to `testHasOnePage`. Limit per page may be changing, don't keep 10 forever.

2017-08-23 04:19 UTC, at-vietpham commented on tests/Browser/AdminListDailyMenuTest.php
> +        $foods = factory(Food::class, 10)->create(['category_id' => 1]);
Use `factory(Food::class, 10)` is not good. You create 10 record -> count -> compare with 10. What happen when limit per page changed?
For example:
`ITEMS_PER_PAGE` in model `Food` changed to 5. So on one page, we have 5 records. You create 10 records but in list display only 5. Your test fails.

2017-08-23 04:19 UTC, at-vietpham commented on tests/Browser/AdminListDailyMenuTest.php
> +    public function testPaginationMorethan10Rows()
If you want to test case list has many pages. Function name should be `testPagination`

2017-08-23 04:19 UTC, at-vietpham commented on tests/Browser/AdminListDailyMenuTest.php
> +            $objectCount = $browser->elements('.table tr');
You can check with element .table tbody tr to get correct data record.

2017-08-23 06:46 UTC, at-vietpham commented
LGTM 😄

2017-08-24 07:17 UTC, ghost approved these changes
LGTM

2017-08-24 07:17 UTC, merged