Admin - Order - Detail Order
AT-PHPIntership/food-market-order pull request #125
Opened 2017-08-16 08:35 UTC by at-vudang

2017-08-17 02:02 UTC, at-nguyenvo commented
Vũ fix conflict giúp anh nhé.

2017-08-18 07:26 UTC, ghost reviewed
Pls check my comment

2017-08-18 07:26 UTC, at-nguyenvo commented on app/Http/Controllers/OrderController.php
> +                ->orWhere('payment', 'like', '%' . $request->keyword . '%');
Using Trait Search.

2017-08-18 07:26 UTC, at-nguyenvo commented on resources/views/orders/show.blade.php
> +                                <th></th>
change to ```<th colspan="5">```

2017-08-18 09:05 UTC, at-vudang commented on app/Http/Controllers/OrderController.php
> +                ->orWhere('payment', 'like', '%' . $request->keyword . '%');
Branch search-module will update it.

2017-08-22 01:44 UTC, ghost requested changes
pls check cmt

2017-08-22 01:44 UTC, at-vienle commented on app/Http/Controllers/OrderController.php
> +        $order = $this->order->with('orderItems.itemtable')->with('user')->find($id);
should use findOrFail

2017-08-22 01:44 UTC, at-vienle commented on app/Http/Controllers/OrderController.php
> +                    $status = Response::HTTP_NOT_FOUND;
should use `BAD_REQUEST` in this case not `HTTP_NOT_FOUND`

2017-08-22 01:44 UTC, at-vienle commented on app/Http/Controllers/OrderController.php
> +    public function deleteItem($id)
this method should be in `OrderItemController`

2017-08-22 01:44 UTC, at-vienle commented on app/Http/Controllers/OrderController.php
> +            $orderItem = OrderItem::with('itemtable')->with('order')->find($id);
hàm `find` nếu tìm ko thấy thì nó trả về `null` không có exception nào cả, nên chỗ try ...catch này vô ích. Nếu muốn try catch thì phải dùng `findOrFail`

2017-08-22 01:44 UTC, at-vienle commented on app/Http/Controllers/OrderController.php
> +            $quantityChange = $orderItem->quantity - $quantityChange;
chỗ này bị lặp code, không sử dụng lại được. Và logic đặt ở controller như thế này không hay.
Nên viết 1 hàm ở model `Order` update lại payment, total,... dựa theo cái oderItem của nó.

2017-08-22 01:44 UTC, at-vienle commented on public/js/main.js
> +    $('.quantity-order-item').change(function () {
👍

2017-08-22 04:00 UTC, ghost requested changes
pls check cmt

2017-08-22 04:00 UTC, at-vienle commented on app/Http/Controllers/OrderItemController.php
> +    public function update(Request $request, $id)
hàm này thao tác đến nhiều bảng csdl nên cần phải sử dụng transaction

2017-08-22 04:00 UTC, at-vienle commented on app/Http/Controllers/OrderItemController.php
> +    public function destroy($id)
hàm này cũng cần transaction

2017-08-22 04:00 UTC, at-vienle commented on app/Order.php
> +    public function updatePayment(OrderItem $orderItem, $quantity)
hàm này để dùng chung được cho nhiều chỗ thì ko nên truyền `$orderItem` hay `$quantity` vào. Ở đây là cập nhật lại `total_price` cho order thôi, không cần quan tâm đến có sự kiện gì xảy ra đối với orderItem, vậy thì mới có thể dùng chung được cho các thay đổi ở orderItem
- có orderItem mới
- xoá  orderItem
- orderItem update quantity

Nghĩa là sum toàn bộ price của các orderItem hiện tại trong DB và update vào order.

2017-08-22 05:01 UTC, at-vudang commented on app/Http/Controllers/OrderItemController.php
> +    public function update(Request $request, $id)
Em nghĩ chỗ này mình có if else try catch các hàm save(), delete() rồi và quy trình theo thứ tự, nên không biết có cần thiết thêm transaction vào code không ạ.

2017-08-22 08:41 UTC, ghost requested changes
pls check my cmt

2017-08-22 08:41 UTC, at-vienle commented on app/Http/Controllers/OrderItemController.php
> +    public function update(Request $request, $id)
OK, nhưng lần sau nên sử dụng transaction vì lúc đó code sẽ ngắn gọn hơn, không cần if - else

2017-08-22 08:41 UTC, at-vienle commented on app/Order.php
> +    public function updateTotalPrice($id)
Hàm này viết đúng rồi, nhưng không cần truyền `$id` vào làm gì, Eloquent của Laravel viết theo dạng ActiveRecord nên mỗi object của Order có property là các column trong DB luôn. Nên sẽ lấy được id từ ngay trong chính object đó. 
`$this->id` , không cần phải query lại.

2017-08-22 08:41 UTC, at-vienle commented on app/Order.php
> +        $order = Order::with('orderItems.itemtable')->findOrFail($id);
phải lấy cả `orderItems` lẫn `orderItems. itemtable`

2017-08-22 08:41 UTC, at-vienle commented on app/Order.php
> +        $order = Order::with('orderItems.itemtable')->findOrFail($id);
```php
$this->load('orderItems', 'orderItems.itemtable');
$this->total_price = $this->orderItems->sum(function($item){
    return $item->price * $item->itemtable->price;
});
return $this->save();

2017-08-22 09:30 UTC, at-vudang commented on app/Order.php
> +        $order = Order::with('orderItems.itemtable')->findOrFail($id);
with('orderItems.itemtable') thế nó trả ra đối tượng Order trong đó có các OrderItem và mà mỗi OrderItem sẽ chứa một Item anh.

2017-08-23 04:12 UTC, ghost approved these changes
LGTM

2017-08-23 04:12 UTC, merged