Folder structure
AT-PHPIntership/food-market-order pull request #63
Opened 2017-07-25 09:34 UTC by at-dungvan

update folder structure for backend site

2017-07-31 09:46 UTC, ghost reviewed
File .env là không được push lên git nha. Em đưa vào gitignore luôn giúp anh.

2017-07-31 09:46 UTC, at-nguyenvo commented on resources/views/admin/includes/script.blade.php
> +</script>
Remove code không cần thiết ra nhé em.

2017-07-31 09:48 UTC, at-vienle commented
Cấu trúc thì đúng rồi nhưng đặt tên thì chưa đúng. Nên đặt theo chuẩn của Laravel, tên file view phải giống tên function trong controller. 
- create.blade.php
- edit.blade.php
- index.blade.php
- show.blade.php

2017-07-31 09:49 UTC, at-vienle commented
Thư mục `includes` nên move vào trong thư mục `layouts` vì thư mục này chỉ dùng cho `layouts` thôi. Nên đổi tên lại thành `partials` thì hay hơn

2017-07-31 09:50 UTC, at-vienle commented
`pageheader.blade.php` không nên đặt tên theo kiểu viết liền 2 từ vào thế này.

2017-07-31 10:05 UTC, at-dungvan commented
Em update cấu trúc thư mục như sau anh xem đã ổn chưa ạ
- `admin`
    - `dashboard.blade.php`
    - `suppliers`
        - `index.blade.php`
        - `create.blade.php`
        - `update.blade.php`
    - `categories`
        - `index.blade.php`
        - `create.blade.php`
        - `update.blade.php`
    - `daily-menus`
        - `index.blade.php`
        - `show.blade.php`
        - `create.blade.php`
        - `update.blade.php`
    - `foods`
        - `index.blade.php`
        - `show.blade.php`
        - `create.blade.php`
        - `update.blade.php`
    - `partials`
        - `aside.blade.php`
        - `footer.blade.php`
        - `header.blade.php`
        - `main_header.blade.php`
        - `script.blade.php`
        - `style.blade.php`
        - `master.blade.php`
    - `materials`
        - `index.blade.php`
        - `show.blade.php`
        - `create.blade.php`
        - `update.blade.php`
    - `orders`
        - `index.blade.php`
        - `show.blade.php`
    - `users`
        - `index.blade.php`
        - `show.blade.php`
        - `create.blade.php`
        - `update.blade.php`

2017-07-31 10:39 UTC, at-vienle commented
`master.blade.php` nằm trong thư mục `partials` là ko đúng rồi.

- layouts
  - partials
    - header.blade.php
    - footer.blade.php
  - master.blade.php

2017-07-31 10:44 UTC, at-dungvan commented
em fix xong anh check lại giúp em!

2017-07-31 10:48 UTC, at-vienle commented
layouts là cha của partials, chứ ko phải ngược lại

2017-07-31 11:02 UTC, at-vienle commented
👍 LGTM

2017-08-01 02:46 UTC, ghost requested changes
pls check my cmt

2017-08-01 02:46 UTC, at-vienle commented on resources/views/admin/layouts/partials/script.blade.php
> +<script>
remove this, we don't use script like this

2017-08-01 03:22 UTC, ghost approved these changes

2017-08-01 03:22 UTC, merged