migration full version
AT-PHPIntership/food-market-order pull request #70
Opened 2017-07-28 19:00 UTC by at-dungvan

2017-08-01 02:54 UTC, at-vienle commented
@at-dungvan dung
This PR is too big, please separate migrations, models,...

2017-08-03 02:29 UTC, ghost requested changes
check my cmt

2017-08-03 02:29 UTC, at-vienle commented on database/migrations/2017_07_28_175306_create_users_table.php
> +            $table->timestamp('deleted_at')->nullable();
use `softDelete` instead

2017-08-04 02:57 UTC, at-duyho commented on database/migrations/2017_07_28_175306_create_users_table.php
> +            $table->boolean('gender')->nullable();
you should use comment statement to define value. for example: 
$table->tinyInteger('send_type')->default(1)
            ->comment = 'IMMEDIATELY = 1; APPOINTMENT = 2; PAUSE = 3; END = 4';

2017-08-04 02:58 UTC, at-duyho commented on database/migrations/2017_07_28_175306_create_users_table.php
> +            $table->boolean('is_admin')->default(0);
-you should use comment statement to define value.

2017-08-04 02:59 UTC, at-duyho commented on database/migrations/2017_07_28_175306_create_users_table.php
> +            $table->boolean('is_active')->nullable();
-you should use comment statement to define value. and set default value.

2017-08-04 03:03 UTC, at-duyho commented on database/migrations/2017_07_28_175345_create_materials_table.php
> +            $table->tinyInteger('status')->default(0);
-you should use comment statement to define value.

2017-08-04 03:04 UTC, at-duyho commented on database/migrations/2017_07_28_175424_create_orders_table.php
> +            $table->boolean('status');
-you should use comment statement to define value and set default value.

2017-08-04 03:04 UTC, at-duyho commented on database/migrations/2017_07_28_175424_create_orders_table.php
> +            $table->integer('user_id')->unsigned()->nullable();
-not allow nullable.

2017-08-04 03:08 UTC, at-duyho commented on database/migrations/2017_07_28_175515_create_order_items_table.php
> +            $table->integer('target_id')->unsigned();
-$table->morphs('targetable');

2017-08-04 03:11 UTC, at-duyho commented on database/migrations/2017_07_28_175515_create_order_items_table.php
> +            $table->string('target_type');
-you should use $table->morphs('targetable') instead of $table->integer('target_id')->unsigned() and $table->string('target_type').

2017-08-04 03:13 UTC, ghost approved these changes
Check comment. thank you!

2017-08-07 03:03 UTC, ghost requested changes
Check comment. please!

2017-08-07 10:56 UTC, ghost requested changes
Check my comment. thank you!

2017-08-08 08:45 UTC, ghost approved these changes
LGTM

2017-08-09 10:36 UTC, merged