List users layout
AT-PHPIntership/food-market-order pull request #71
Opened 2017-07-29 14:35 UTC by at-dungvan

2017-08-07 10:48 UTC, at-duyho commented on app/Http/Controllers/UserController.php
>  class UserController extends Controller
-you should create constructor to use DI in laravel.

2017-08-07 10:50 UTC, at-duyho commented on app/Http/Controllers/UserController.php
> +            flash('can not delete yourself!')->error();
define message to lang file.

2017-08-07 10:50 UTC, at-duyho commented on app/Http/Controllers/UserController.php
> +                flash('delete successfully!')->success();
-define message to lang file

2017-08-07 10:50 UTC, at-duyho commented on app/Http/Controllers/UserController.php
> +                flash('can not delete yourself!')->error();
-define message to lang file

2017-08-07 10:51 UTC, ghost requested changes
check comment.please!

2017-08-08 04:03 UTC, at-duyho commented on app/Http/Controllers/UserController.php
>          if (!isset($listUsers)) {
what's $listUsers?

2017-08-08 04:09 UTC, at-duyho commented on app/Http/Controllers/UserController.php
> +            flash(trans('user/message.delete-error'))->error();
you should use user::message.delete-error instead of user/message.delete-error.

2017-08-08 04:09 UTC, ghost requested changes
pleas check comment.

2017-08-08 04:41 UTC, at-dungvan commented on app/Http/Controllers/UserController.php
> +            flash(trans('user/message.delete-error'))->error();
i just do this, and it not work!!

2017-08-08 09:12 UTC, at-dungvan commented on app/Http/Controllers/UserController.php
>          if (!isset($listUsers)) {
this is a list of users get from database and return to index to show the users record

2017-08-09 08:20 UTC, at-duyho commented on app/Http/Controllers/UserController.php
> +
remove blank line.

2017-08-09 08:21 UTC, at-duyho commented on app/Http/Controllers/UserController.php
> +
remove blank line.

2017-08-09 08:21 UTC, at-duyho commented on app/Http/Controllers/UserController.php
remove blank line.

2017-08-09 08:23 UTC, at-duyho commented on composer.json
> +        "laracasts/flash": "^3.0",
why this pull request like https://github.com/AT-PHPIntership/food-market-order/pull/72/files

2017-08-09 08:24 UTC, ghost requested changes
Check comment.

2017-08-09 08:46 UTC, at-dungvan commented on composer.json
> +        "laracasts/flash": "^3.0",
this is list and delete module, the pull  https://github.com/AT-PHPIntership/food-market-order/pull/72/files
is create module, it different!

2017-08-09 08:46 UTC, at-dungvan commented
check my comment! thank you!

2017-08-10 01:23 UTC, at-duyho commented on resources/views/users/index.blade.php
> +    @if(!isset($users))
why do you use negative condition?

2017-08-10 01:26 UTC, ghost requested changes
Check comment.

2017-08-10 02:01 UTC, at-dungvan commented on resources/views/users/index.blade.php
> +    @if(!isset($users))
if the $users is null, the view just view `Nothing to show!` in if statement, it easy to read the code, i think the positive have the same thing, but the line `Nothing to show!` in the bottom, it so hard to view the code!

2017-08-10 05:00 UTC, at-dungvan commented
check my comment! please!

2017-08-11 01:29 UTC, ghost approved these changes
LGTM

2017-08-11 02:15 UTC, merged