Create user layout
AT-PHPIntership/food-market-order pull request #72
Opened 2017-07-29 15:09 UTC by at-dungvan

2017-08-07 10:45 UTC, at-duyho commented on app/Http/Controllers/UserController.php
> +        $this->validate($request, [
-you should create class Request to check validation.

2017-08-07 10:46 UTC, at-duyho commented on app/Http/Controllers/UserController.php
>  {
-you should create constructor to use DI of laravel.

2017-08-07 10:46 UTC, ghost requested changes
check my comment. please.

2017-08-08 09:08 UTC, at-dungvan commented on app/Http/Controllers/UserController.php
>  {
check again please!

2017-08-08 10:22 UTC, at-duyho commented on app/Http/Controllers/UserController.php
>  {
I seen.

2017-08-08 10:26 UTC, at-duyho commented on app/Http/Controllers/UserController.php
> +        if ($user->save()) {
-$arr = $request->all();
-$arr['image'] = $nameFile;
-You should use $this->user->save($arr);

2017-08-08 10:28 UTC, at-duyho commented on app/Http/Controllers/UserController.php
> +        $user->password = bcrypt($request->get('password'));
you shoul use event of model.https://laravel.com/docs/5.4/eloquent#events (use observer)

2017-08-08 10:29 UTC, ghost requested changes
Check comment.

2017-08-08 10:32 UTC, at-duyho commented on app/Http/Controllers/UserController.php
> +        if ($request->hasFile('image')) {
- create common function.

2017-08-09 08:15 UTC, at-duyho commented on app/Http/Controllers/UserController.php
> +
remove blank line.

2017-08-09 08:16 UTC, at-duyho commented on app/Http/Controllers/UserController.php
> +        return redirect()->route('users.index');
remove blank line.

2017-08-09 08:16 UTC, at-duyho commented on app/User.php
> +
remove blank line.

2017-08-09 08:17 UTC, ghost requested changes
check comment.

2017-08-09 08:41 UTC, at-dungvan commented
i updated, check again please! thank you!

2017-08-10 01:29 UTC, at-duyho commented on app/Http/Controllers/UserController.php
> +        }
I think you should define common function for save image. After, you can use it everywhere you want.

2017-08-10 01:31 UTC, ghost requested changes
Check comment

2017-08-10 07:10 UTC, at-duyho commented on app/User.php
> +use function foo\func;
what's foo\func?

2017-08-10 07:11 UTC, at-duyho commented on app/Http/Controllers/UserController.php
> +    public function store(UserPostRequest $request)
refactor this function. create common save image function.

2017-08-10 07:11 UTC, ghost requested changes
check comment.

2017-08-10 08:16 UTC, at-dungvan commented on app/Http/Controllers/UserController.php
> +    public function store(UserPostRequest $request)
i did it, please check agains

2017-08-11 02:15 UTC, ghost approved these changes
LGTM

2017-08-11 07:23 UTC, merged