Detail user layout
AT-PHPIntership/food-market-order pull request #73
Opened 2017-07-29 15:18 UTC by at-dungvan

2017-08-07 10:52 UTC, at-duyho commented on app/Http/Controllers/UserController.php
> +        $user = User::find($id);
-you should use findOrfail function.

2017-08-07 10:53 UTC, at-duyho commented on app/Http/Controllers/UserController.php
> +        $totalOrders = Order::where(['user_id' => $id])->get();
-you should use with function in laravel. Get relationship in laravel.

2017-08-07 10:54 UTC, ghost requested changes
-check comment. please.

2017-08-09 08:25 UTC, at-duyho commented on app/Http/Controllers/UserController.php
> +        if ($detailUser = $this->user->findOrFail($id)) {
what's $detailUser?

2017-08-09 08:27 UTC, at-duyho commented on app/Http/Controllers/UserController.php
> +            $totalOrders = $detailUser->orders()->get();
refactor it. if your data has a lot of records, your sever will die.

2017-08-09 08:28 UTC, at-duyho commented on composer.json
> +        "laracasts/flash": "^3.0",
while this pull request like https://github.com/AT-PHPIntership/food-market-order/pull/72/files?

2017-08-09 08:29 UTC, ghost requested changes
Check comment.

2017-08-10 02:18 UTC, at-dungvan commented on app/Http/Controllers/UserController.php
> +        if ($detailUser = $this->user->findOrFail($id)) {
the $detailUser is the user response to view to show detail

2017-08-10 02:22 UTC, at-dungvan commented on composer.json
> +        "laracasts/flash": "^3.0",
this flash to use the message session.

2017-08-10 07:25 UTC, at-duyho commented on app/Http/Controllers/UserController.php
> +        if ($userToShow = $this->user->with('orders')->findOrFail($id)) {
what's $userToShow?

2017-08-10 07:26 UTC, at-duyho commented on resources/views/users/show.blade.php
> +                                        {{ $user->gender == 1 ? __('Male') : __('Female') }}
what's 1?

2017-08-10 07:26 UTC, at-duyho commented on resources/views/users/show.blade.php
> +                                        {{ $user->is_admin == 1? __('Admin') : __('Normal User') }}
what's 1?

2017-08-10 07:26 UTC, ghost requested changes
check comment.

2017-08-10 15:02 UTC, at-dungvan commented on resources/views/users/show.blade.php
> +                                        {{ $user->gender == 1 ? __('Male') : __('Female') }}
gender is boolean type (has description in branch migration), gender = 0 -> female, gender = 1 -> male

2017-08-10 15:03 UTC, at-dungvan commented on resources/views/users/show.blade.php
> +                                        {{ $user->is_admin == 1? __('Admin') : __('Normal User') }}
is_admin is boolean type (has description in branch migration), is_admin = 1 -> admin user, is_admin = 0 -> normal user

2017-08-11 01:56 UTC, at-duyho commented on app/Http/Controllers/UserController.php
> +use App\Order;
Do you use Order in this file?

2017-08-11 01:57 UTC, at-duyho commented on app/Http/Controllers/UserController.php
> +        if ($userToShow = $this->user->with('orders')->findOrFail($id)) {
what't $userToShow?

2017-08-11 01:58 UTC, at-duyho commented on resources/views/users/show.blade.php
> +                                        {{ $user->gender == 1 ? __('Male') : __('Female') }}
you should define constant to another developer can understand.

2017-08-11 01:58 UTC, at-duyho commented on resources/views/users/show.blade.php
> +                                        {{ $user->is_admin == 1? __('Admin') : __('Normal User') }}
you should define constant to another developer can understand it.

2017-08-11 01:59 UTC, at-duyho commented on resources/views/users/show.blade.php
> +                                        {{ count($user->orders()) }}
you should run count order sql when get relationship.

2017-08-11 02:00 UTC, at-duyho commented on resources/views/users/show.blade.php
> +                                            @foreach($user->orders as $order)
you show all orders of user?

2017-08-11 02:00 UTC, ghost requested changes
check comment.

2017-08-11 07:31 UTC, at-dungvan commented on resources/views/users/show.blade.php
> +                                        {{ count($user->orders()) }}
yes! this detail user show user information and user's order history

2017-08-11 07:32 UTC, at-dungvan commented on resources/views/users/show.blade.php
> +                                            @foreach($user->orders as $order)
yes! this detail user show user information and user's order history

2017-08-11 07:32 UTC, at-dungvan commented on resources/views/users/show.blade.php
> +                                        {{ count($user->orders()) }}
sorry, i don't understand you mean!

2017-08-14 02:36 UTC, ghost requested changes
check comment.

2017-08-16 07:44 UTC, at-duyho commented on app/Http/Controllers/UserController.php
> +        if ($userToShow = $this->user->with('orders')->findOrFail($id)) {
why do you use if statement?

2017-08-16 07:44 UTC, ghost requested changes
check comment

2017-08-17 01:53 UTC, at-duyho commented on app/Http/Controllers/UserController.php
> +        $userToShow = $this->user->with('orders')->findOrFail($id);
I think you should take 10~15 orders of user.

2017-08-17 01:53 UTC, ghost requested changes
check comment

2017-08-17 04:01 UTC, at-dungvan commented on app/Http/Controllers/UserController.php
> +        $userToShow = $this->user->with('orders')->findOrFail($id);
i update to pagination, check again, thank you!

2017-08-17 06:54 UTC, at-duyho commented on app/Http/Controllers/UserController.php
> +        $listOrders = Order::where('user_id', $id)->paginate(Order::ITEMS_PER_PAGE);
why you get again list orders?

2017-08-17 06:54 UTC, ghost requested changes
check comment

2017-08-18 09:30 UTC, ghost approved these changes
LGTM

2017-08-21 09:13 UTC, ghost requested changes
pls check my cmt

2017-08-21 09:13 UTC, ghost commented on app/Http/Controllers/UserController.php
> +        $totalOrders = Order::where('user_id', $id)->count();
No need this variable, the total order is already in the pagination.

2017-08-21 09:13 UTC, ghost commented on resources/views/users/show.blade.php
> +                                         src="/images/users/{{ $user->image }}" data-original-title="Usuario">
use `asset`

2017-08-21 09:13 UTC, at-vienle commented on resources/views/users/show.blade.php
> +                                            <td>@if($order->status == 0)
please don't hardcode

2017-08-22 08:19 UTC, ghost approved these changes
LGTM

2017-08-22 08:19 UTC, merged