create factories and seeder
AT-PHPIntership/food-market-order pull request #78
Opened 2017-08-01 04:35 UTC by at-dungvan

2017-08-04 03:25 UTC, ghost approved these changes
check comment. please

2017-08-04 03:25 UTC, at-duyho commented on database/factories/ModelFactory.php
> +        'status' => random_int(0, 3)
-why did you define it is boolean?

2017-08-04 03:25 UTC, at-duyho commented on database/factories/ModelFactory.php
> +            'target_id' => $faker->randomElement(App\Food::pluck('id')->toArray()),
-update column name with morphy column.

2017-08-04 03:25 UTC, at-duyho commented on database/factories/ModelFactory.php
> +            'target_id' => $faker->randomElement(App\Material::pluck('id')->toArray()),
-update column name with morphy column.

2017-08-04 03:26 UTC, ghost requested changes
check comment. please.

2017-08-07 03:05 UTC, ghost requested changes
Check comment, please!

2017-08-07 10:58 UTC, ghost requested changes
check my comment. thank you!

2017-08-08 10:37 UTC, at-dungvan commented on database/factories/ModelFactory.php
> +        'status' => random_int(0, 3)
i was changes this to tinyInteger in migration! thank you!

2017-08-09 03:03 UTC, at-duyho commented on database/factories/ModelFactory.php
> +        'status' => random_int(0, 3)
ok. thank you!

2017-08-09 03:06 UTC, ghost approved these changes
LGTM

2017-08-09 10:37 UTC, merged