update folder structure
AT-PHPIntership/food-market-order pull request #92
Opened 2017-08-02 10:14 UTC by at-dungvan

2017-08-02 10:43 UTC, ghost requested changes
- Fix conflict 
- correct file mode: 
 - file: 644
 - folder: 755
- correct the view name : index, create, edit, show (edit instead of update)

2017-08-02 10:43 UTC, at-vienle commented on .gitignore
> +<<<<<<< HEAD
resolve conflict

2017-08-02 10:46 UTC, at-dungvan commented on .gitignore
> +<<<<<<< HEAD
ok anh

2017-08-03 02:27 UTC, ghost approved these changes

2017-08-03 02:27 UTC, merged