Admin daily menu view list (backend)
AT-PHPIntership/food-market-order pull request #94
Opened 2017-08-04 04:48 UTC by at-hungnguyen

2017-08-04 07:01 UTC, at-duyho commented on app/DailyMenu.php
> +    /**
why don't you define table name for ORM model.

2017-08-04 07:05 UTC, at-duyho commented on app/DailyMenu.php
> +        return DB::table('daily_menus')
You should use self instead of DB.

2017-08-04 07:06 UTC, at-duyho commented on app/Http/Controllers/Auth/RegisterController.php
>          return User::create([
you should use key of array data same with column name.

2017-08-04 07:08 UTC, at-duyho commented on app/Http/Controllers/Auth/RegisterController.php
>              'password' => bcrypt($data['password']),
you should use event of model. https://laravel.com/docs/5.4/eloquent#events

2017-08-04 07:11 UTC, ghost requested changes
check my comment. thank you!

2017-08-04 08:53 UTC, at-hungnguyen commented on app/Http/Controllers/Auth/RegisterController.php
>          return User::create([
From @at-dungvan code

2017-08-04 08:54 UTC, at-hungnguyen commented on app/Http/Controllers/Auth/RegisterController.php
>              'password' => bcrypt($data['password']),
From @at-dungvan code, i just edit to use register and login function

2017-08-04 08:54 UTC, at-hungnguyen commented
I updated, please check it again
THank you so much :smile:

2017-08-04 09:47 UTC, at-duyho commented on app/DailyMenu.php
> +        return DailyMenu::select('date')
why don't you use self?

2017-08-04 09:48 UTC, at-duyho commented on app/Http/Controllers/Auth/RegisterController.php
>          return User::create([
so, you have to remove this file in pull request.

2017-08-04 09:49 UTC, ghost requested changes
please check my comment. please.
and you have to use: git comment --amend and git push --force origin "name branch" when you edit pull request.

2017-08-04 10:44 UTC, at-hungnguyen commented
I updated and i forgot doing git commit --amend. I will do it for later
Thank you so much

2017-08-07 03:31 UTC, at-duyho commented on app/DailyMenu.php
> +    public static function getAll()
remove static.

2017-08-07 03:33 UTC, at-duyho commented on app/Http/Controllers/DailyMenuController.php
> +    /**
you should declare constructor function and use DI in laravel.

2017-08-07 03:33 UTC, ghost requested changes
Check my comment. please.

2017-08-07 09:55 UTC, at-hungnguyen commented
I updated, please check it again!
Thank you so much

2017-08-08 03:08 UTC, at-duyho commented on app/Http/Controllers/DailyMenuController.php
> +    protected $dailyMenus;
-object must be a singular noun

2017-08-08 03:08 UTC, at-duyho commented on app/Http/Controllers/DailyMenuController.php
> +    public function __construct(DailyMenu $dailyMenus)
-object must be a singular noun

2017-08-08 15:59 UTC, at-hungnguyen commented
I updated, please check it again, thank you so much

2017-08-09 03:08 UTC, ghost reviewed
check comment.

2017-08-09 03:09 UTC, ghost approved these changes
Check comment.

2017-08-09 08:56 UTC, at-duyho commented on app/DailyMenu.php
> +        return self::select('date')
-you should move this code in controller.

2017-08-09 08:56 UTC, at-duyho commented on app/Http/Controllers/DailyMenuController.php
> +use App\Food;
Do you use Food?

2017-08-09 08:59 UTC, ghost requested changes
Check comment

2017-08-10 01:34 UTC, ghost approved these changes
LGTM

2017-08-10 08:23 UTC, merged