Admin listfood
AT-PHPIntership/food-market-order pull request #96
Opened 2017-08-04 06:51 UTC by at-hieuvo

2017-08-07 17:16 UTC, at-nguyenvo commented on resources/views/foods/index.blade.php
> +            <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
Change div id ```example1_wrapper```. Pls remember do not used id with name ```example``` or like that.

2017-08-07 17:16 UTC, at-nguyenvo commented on resources/views/foods/index.blade.php
> +                               aria-describedby="example1_info">
Change ```example1_info ```. Pls remember do not used  ```example``` or like that.

2017-08-07 17:16 UTC, at-nguyenvo commented on resources/views/foods/index.blade.php
> +                                <th style="width: 1em">{{ trans('foods/listfoods.id') }}</th>
Do not used css inline

2017-08-07 17:16 UTC, at-nguyenvo commented on resources/views/layouts/partials/script.blade.php
> +
Remove line null

2017-08-07 17:16 UTC, at-nguyenvo commented on resources/views/layouts/partials/style.blade.php
> +
Remove line null

2017-08-08 10:37 UTC, at-duyho commented on app/Food.php
> +    public function categories()
-you should change categories to category.

2017-08-08 10:38 UTC, at-duyho commented on app/Http/Controllers/FoodController.php
> +    public function __construct(Food $foods)
-object should be a singular.

2017-08-08 10:39 UTC, at-duyho commented on app/Http/Controllers/FoodController.php
> +    protected $foods;
-object should be a singular.

2017-08-08 10:40 UTC, at-duyho commented on resources/views/foods/index.blade.php
> +                                    <td>{{ $food->categories->name }}</td>
-you have to use with function to get category  when you get list food in controller.

2017-08-08 10:41 UTC, ghost requested changes
check comment.

2017-08-09 01:28 UTC, at-hieuvo commented
I updated, please check it again. Thank you so much!

2017-08-09 03:12 UTC, at-duyho commented on composer.lock
> +{
why do you commit this file?

2017-08-09 03:14 UTC, at-duyho commented on resources/views/foods/index.blade.php
> +                                <th class="col-md-1">{{ trans('foods/listfoods.id') }}</th>
you should use ':' instead of '/'. please check it. thank you!

2017-08-09 03:14 UTC, ghost requested changes
Check comment.

2017-08-09 08:32 UTC, ghost approved these changes
check comment

2017-08-09 08:51 UTC, at-duyho commented on app/Http/Controllers/FoodController.php
> +use App\Category;
Do you use Category class in this file.

2017-08-09 08:51 UTC, at-duyho commented on app/Http/Controllers/FoodController.php
> +use Illuminate\Support\Facades\DB;
Do you use DB in this file?

2017-08-09 08:52 UTC, ghost requested changes
Sorry, I'm mistake. check comment. thank you.

2017-08-09 09:11 UTC, at-hieuvo commented on app/Http/Controllers/FoodController.php
> +use Illuminate\Support\Facades\DB;
I forget remove it. I update now. Thank you very much

2017-08-10 01:36 UTC, ghost approved these changes
LGTM

2017-08-11 02:03 UTC, at-duyho commented on resources/views/foods/index.blade.php
> +                            @foreach($foods as $food)
what do you display when foods is null?

2017-08-11 02:03 UTC, ghost requested changes
check comment

2017-08-11 06:33 UTC, ghost approved these changes
LGTM

2017-08-11 07:21 UTC, merged